"""empty message

Revision ID: 0c2632cc1140
Revises: 3f4cf4499441
Create Date: 2024-09-29 18:19:44.172356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2632cc1140'
down_revision = '3f4cf4499441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inserts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inserts', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
