"""empty message

Revision ID: 25c7409c8d3f
Revises: 5894dd08b3fe
Create Date: 2024-08-20 15:56:45.190162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c7409c8d3f'
down_revision = '5894dd08b3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adhesive',
    sa.Column('material', sa.String(length=64), nullable=False),
    sa.Column('coating', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('bond_strength_adhesive', sa.Float(), nullable=False),
    sa.Column('normal_shear_strength', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['coating'], ['coating.Name'], ),
    sa.ForeignKeyConstraint(['material'], ['material.Name'], ),
    sa.PrimaryKeyConstraint('material', 'coating', 'temperature', name='adhesive_pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adhesive')
    # ### end Alembic commands ###
