"""Добавление таблицы type_id

Revision ID: 26378875b83f
Revises: 599d2904ca17
Create Date: 2024-09-23 16:30:45.749143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26378875b83f'
down_revision = '599d2904ca17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_material_type', 'material_type', ['type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')

    op.create_table('_alembic_tmp_material',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('PropPhysics', sa.VARCHAR(length=64), nullable=True),
    sa.Column('Structure', sa.TEXT(), nullable=True),
    sa.Column('Properties', sa.VARCHAR(length=120), nullable=True),
    sa.Column('Gost', sa.VARCHAR(length=64), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['material_type.id'], name='fk_material_type'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
