"""Удаление столбца стойкости

Revision ID: 268bfcbce998
Revises: e5422127a970
Create Date: 2024-10-11 10:35:27.027149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268bfcbce998'
down_revision = 'e5422127a970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_parameters', schema=None) as batch_op:
        batch_op.drop_column('durability')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('durability', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
