"""Удаление столбца new

Revision ID: 3f4cf4499441
Revises: 62479ff6941c
Create Date: 2024-09-27 23:38:18.558280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4cf4499441'
down_revision = '62479ff6941c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adhesive', schema=None) as batch_op:
        batch_op.drop_column('new_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adhesive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
