"""empty message

Revision ID: 5762a8498974
Revises: 7c7a80031854
Create Date: 2024-05-16 10:02:12.323062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5762a8498974'
down_revision = '7c7a80031854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomeded_speed',
    sa.Column('Materials', sa.String(length=64), nullable=False),
    sa.Column('Tool', sa.String(length=64), nullable=False),
    sa.Column('Coating', sa.String(length=64), nullable=False),
    sa.Column('SpindleSpeed', sa.Integer(), nullable=True),
    sa.Column('FeedTable', sa.Float(), nullable=True),
    sa.Column('Roughness', sa.Float(), nullable=True),
    sa.Column('Hardening', sa.Float(), nullable=True),
    sa.Column('Durability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['Coating'], ['coating.name'], ),
    sa.ForeignKeyConstraint(['Materials'], ['material.name'], ),
    sa.ForeignKeyConstraint(['Tool'], ['toolsdate.name'], ),
    sa.PrimaryKeyConstraint('Materials', 'Tool', 'Coating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recomeded_speed')
    # ### end Alembic commands ###
