"""empty message

Revision ID: 5894dd08b3fe
Revises: 58f24177fcf6
Create Date: 2024-05-23 13:50:44.974064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5894dd08b3fe'
down_revision = '58f24177fcf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NanoHardness', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('TemratureResistance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('KoefficientFriction', sa.Float(), nullable=True))
        batch_op.alter_column('MaxThickness',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=32),
               existing_nullable=True)

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gost', sa.String(length=64), nullable=True))

    with op.batch_alter_table('tool_geometry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FrontAngle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('SpiralAngle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('FRearAngle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('SRearAngle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('MainRearAngle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('AngularPitch', sa.String(length=32), nullable=True))
        batch_op.drop_column('geometry_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_geometry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geometry_data', sa.TEXT(), nullable=True))
        batch_op.drop_column('AngularPitch')
        batch_op.drop_column('MainRearAngle')
        batch_op.drop_column('SRearAngle')
        batch_op.drop_column('FRearAngle')
        batch_op.drop_column('SpiralAngle')
        batch_op.drop_column('FrontAngle')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('gost')

    with op.batch_alter_table('coating', schema=None) as batch_op:
        batch_op.alter_column('MaxThickness',
               existing_type=sa.String(length=32),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('KoefficientFriction')
        batch_op.drop_column('TemratureResistance')
        batch_op.drop_column('NanoHardness')

    # ### end Alembic commands ###
