"""empty message

Revision ID: 58f24177fcf6
Revises: 5762a8498974
Create Date: 2024-05-16 18:41:24.466053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f24177fcf6'
down_revision = '5762a8498974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv__files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_graphik_s', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('path_graphik_t', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv__files', schema=None) as batch_op:
        batch_op.drop_column('path_graphik_t')
        batch_op.drop_column('path_graphik_s')

    # ### end Alembic commands ###
