"""empty message

Revision ID: 7c7a80031854
Revises: 
Create Date: 2024-05-15 17:43:02.225281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7a80031854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('MaterialCoating', sa.String(length=64), nullable=True),
    sa.Column('ColorCoating', sa.String(length=32), nullable=True),
    sa.Column('TypeApplication', sa.String(length=64), nullable=True),
    sa.Column('MaxThickness', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coating_Name'), ['name'], unique=True)

    op.create_table('csv__files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename_strengh', sa.String(length=128), nullable=False),
    sa.Column('filename_temrature', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename_strengh'),
    sa.UniqueConstraint('filename_temrature'),
    sa.UniqueConstraint('path')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('prop_physics', sa.String(length=64), nullable=True),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.Column('properties', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_Name'), ['name'], unique=True)

    op.create_table('toolsdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('MaterialTool', sa.String(length=64), nullable=True),
    sa.Column('NumberTeeth', sa.Integer(), nullable=False),
    sa.Column('Diameter', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolsdate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolsdate_Name'), ['name'], unique=True)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Materials', sa.String(length=64), nullable=True),
    sa.Column('Tool', sa.String(length=64), nullable=True),
    sa.Column('Coating', sa.String(length=64), nullable=True),
    sa.Column('SpindleSpeed', sa.Float(), nullable=True),
    sa.Column('FeedTable', sa.Float(), nullable=True),
    sa.Column('DepthCut', sa.Float(), nullable=True),
    sa.Column('WidthCut', sa.Float(), nullable=True),
    sa.Column('LengthPath', sa.Float(), nullable=True),
    sa.Column('Durability', sa.Float(), nullable=True),
    sa.Column('csv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Coating'], ['coating.name'], ),
    sa.ForeignKeyConstraint(['Materials'], ['material.name'], ),
    sa.ForeignKeyConstraint(['Tool'], ['toolsdate.name'], ),
    sa.ForeignKeyConstraint(['csv_id'], ['csv__files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('geometry_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['toolsdate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_geometry')
    op.drop_table('experiments')
    with op.batch_alter_table('toolsdate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolsdate_Name'))

    op.drop_table('toolsdate')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_Name'))

    op.drop_table('material')
    op.drop_table('csv__files')
    with op.batch_alter_table('coating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coating_Name'))

    op.drop_table('coating')
    # ### end Alembic commands ###
