"""Переименование таблицы материалы

Revision ID: 8903526b9340
Revises: 5e009e02a9af
Create Date: 2024-09-26 16:15:33.537345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8903526b9340'
down_revision = '5e009e02a9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('prop_physics', sa.String(length=64), nullable=True),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.Column('properties', sa.String(length=120), nullable=True),
    sa.Column('gost', sa.String(length=64), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['material_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_name'), ['name'], unique=True)

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index('ix_material_Name')

    op.drop_table('material')
    with op.batch_alter_table('adhesive', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'materials', ['material'], ['name'])

    with op.batch_alter_table('coefficients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'])

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'materials', ['Material'], ['name'])

    with op.batch_alter_table('recomeded_speed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'materials', ['Material'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recomeded_speed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'material', ['Material'], ['Name'])

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'material', ['Material'], ['Name'])

    with op.batch_alter_table('coefficients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'material', ['material_id'], ['id'])

    with op.batch_alter_table('adhesive', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'material', ['material'], ['Name'])

    op.create_table('material',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('PropPhysics', sa.VARCHAR(length=64), nullable=True),
    sa.Column('Structure', sa.TEXT(), nullable=True),
    sa.Column('Properties', sa.VARCHAR(length=120), nullable=True),
    sa.Column('Gost', sa.VARCHAR(length=64), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['material_type.id'], name='fk_material_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index('ix_material_Name', ['Name'], unique=1)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_name'))

    op.drop_table('materials')
    # ### end Alembic commands ###
