"""empty message

Revision ID: abff78c13020
Revises: 5894dd08b3fe
Create Date: 2024-07-17 11:26:46.233893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abff78c13020'
down_revision = '5894dd08b3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_speed',
    sa.Column('Material', sa.String(length=64), nullable=False),
    sa.Column('Tool', sa.String(length=64), nullable=False),
    sa.Column('Coating', sa.String(length=64), nullable=False),
    sa.Column('SpindleSpeed', sa.Integer(), nullable=True),
    sa.Column('FeedTable', sa.Float(), nullable=True),
    sa.Column('Roughness', sa.Float(), nullable=True),
    sa.Column('Hardening', sa.Float(), nullable=True),
    sa.Column('Durability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['Coating'], ['coating.Name'], ),
    sa.ForeignKeyConstraint(['Material'], ['material.Name'], ),
    sa.ForeignKeyConstraint(['Tool'], ['toolsdate.Name'], ),
    sa.PrimaryKeyConstraint('Material', 'Tool', 'Coating', name='recomended_speed_pk')
    )
    op.drop_table('recomeded_speed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomeded_speed',
    sa.Column('Material', sa.VARCHAR(length=64), nullable=False),
    sa.Column('Tool', sa.VARCHAR(length=64), nullable=False),
    sa.Column('Coating', sa.VARCHAR(length=64), nullable=False),
    sa.Column('SpindleSpeed', sa.INTEGER(), nullable=True),
    sa.Column('FeedTable', sa.FLOAT(), nullable=True),
    sa.Column('Roughness', sa.FLOAT(), nullable=True),
    sa.Column('Hardening', sa.FLOAT(), nullable=True),
    sa.Column('Durability', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['Coating'], ['coating.Name'], ),
    sa.ForeignKeyConstraint(['Material'], ['material.Name'], ),
    sa.ForeignKeyConstraint(['Tool'], ['toolsdate.Name'], ),
    sa.PrimaryKeyConstraint('Material', 'Tool', 'Coating')
    )
    op.drop_table('recommended_speed')
    # ### end Alembic commands ###
