"""Создание базы даннных экспериментов с данными по износу от пути резания

Revision ID: e5422127a970
Revises: f7bebe0a1050
Create Date: 2024-10-06 00:30:17.874144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5422127a970'
down_revision = 'f7bebe0a1050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_experiment', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_recording', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_column('date_recording')
        batch_op.drop_column('data_experiment')

    # ### end Alembic commands ###
