"""update MillingGeometry

Revision ID: f7bebe0a1050
Revises: 0c2632cc1140
Create Date: 2024-10-02 20:17:52.976566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bebe0a1050'
down_revision = '0c2632cc1140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milling_geometry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_milling', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('diameter_shank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('length_work', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type_shank', sa.String(length=64), nullable=True))
        batch_op.drop_column('angular_pitch')
        batch_op.drop_column('s_rear_angle')
        batch_op.drop_column('front_angle')
        batch_op.drop_column('main_rear_angle')
        batch_op.drop_column('f_rear_angle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milling_geometry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_rear_angle', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('main_rear_angle', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('front_angle', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('s_rear_angle', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('angular_pitch', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('type_shank')
        batch_op.drop_column('length_work')
        batch_op.drop_column('length')
        batch_op.drop_column('diameter_shank')
        batch_op.drop_column('type_milling')

    # ### end Alembic commands ###
